version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/mlapp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/mlapp/app/requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            make setup
            make install
          
      - save_cache:
          paths:
            - ~/.mlapp
          key: v1-dependencies-{{ checksum "~/mlapp/app/requirements.txt" }}
      # run lint!
      - run:
          name: Run lint
          command: |
            ~/.mlapp/bin/activate
            make lint           

